# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://wuhuhu800.github.io
date_format: "ordinal"
title: 问道
subtitle: "学无先后，达者为师"
description: "阿虎的个人博客"
keywords: 问道, 阿虎, Woody
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Hu Wu
organization: woody800.top
organization_url: http://www.woody800.top
github_username: wuhuhu800
location: Beijingn, China
email: gwuhuhu800@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plugins:
  - jekyll-seo-tag
plugins:
  - jekyll-archives
plugins:
  - jekyll-redirect-from

google:
   analytics_id: UA-111499340-1
