# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://wuhuhu800.github.io
date_format: "ordinal"
title: 问道
subtitle: "学无先后，达者为师"
description: "阿虎的个人博客"
keywords: 问道, 阿虎, Woody
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Hu Wu
organization: woody800.top
organization_url: http://www.woody800.top
github_username: wuhuhu800
location: Beijingn, China
email: gwuhuhu800@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wuhuhu800/wuhuhu800.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: wuhuhu800
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wuhuhu800
    repo: wuhuhu800.githib.io
    oauth:
        client_id: 5715ceb3bcbbec50ce6b
        client_secret: dd4d7fdd7f604bef993a283be05fe4b9d854d5e4
# https://github.com/gitalk/gitalk#install
#gitalk:
#    owner: mzlogin
#    repo: blog-comments
#    clientID: d2e1cbbd298958076462
#    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-111499340-1

webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

collections:
  my_collection:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: my_collection
    values:
      layout: page

theme: jekyll-theme-architect